# Generated by Django 4.1.5 on 2023-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-profile-image-png-1-Transparent-Images.png', upload_to='profile_images'),
        ),
    ]
