# Generated by Django 4.1.5 on 2023-02-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='You add your biography', max_length=9999999999999999999999999),
        ),
    ]
