# Generated by Django 4.1.5 on 2023-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0005_alter_post_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='tool',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('CSHARP', 'C#'), ('C', 'C'), ('CPP', 'C++'), ('JS', 'JavaScript'), ('PHP', 'PHP'), ('SWIFT', 'Swift'), ('JAVA', 'Java'), ('GO', 'Go'), ('RUBY', 'Ruby'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('KOTLIN', 'Kotlin'), ('SCALA', 'Scala'), ('RUST', 'Rust'), ('PERL', 'Perl'), ('MATHLAB', 'Mathlab'), ('TYPESCRIPT', 'TypeScript'), ('R', 'R')], max_length=100),
        ),
    ]
