# Generated by Django 4.1.5 on 2023-02-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_alter_post_current_capacity_alter_post_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tool',
        ),
    ]
