# Generated by Django 4.1.5 on 2023-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0012_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tool',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
