# Generated by Django 4.1.5 on 2023-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0013_alter_post_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capacityRatio',
            field=models.FloatField(default=0),
        ),
    ]
