# Generated by Django 4.1.5 on 2023-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0014_post_capacityratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tool',
            field=models.CharField(default=None, max_length=100000000),
        ),
    ]
