# Generated by Django 4.1.7 on 2023-03-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0015_alter_post_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(default=None, max_length=1000000)),
                ('trigger', models.CharField(default=None, max_length=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='musker.post')),
            ],
        ),
    ]
