# Generated by Django 4.1.7 on 2023-03-16 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Post',
            field=models.CharField(default=None, max_length=100000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
