# Generated by Django 4.1.7 on 2023-03-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0017_alter_notification_post_alter_notification_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='musker.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(default=None, max_length=1000000),
        ),
    ]
