# Generated by Django 4.1.7 on 2023-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0019_alter_notification_post_alter_notification_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='textId',
            field=models.TextField(default='<django.db.models.fields.CharField><django.db.models.fields.DateTimeField>', max_length=1000000),
        ),
    ]
