# Generated by Django 4.1.7 on 2023-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0020_notification_textid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='textId',
            field=models.TextField(default='<django.db.models.fields.CharField><django.db.models.fields.DateTimeField><django.db.models.fields.related.ForeignKey>', max_length=1000000),
        ),
    ]
