# Generated by Django 4.2.1 on 2023-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0021_alter_notification_textid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joinedProjects',
            field=models.IntegerField(default=0),
        ),
    ]
