# Generated by Django 4.2.1 on 2023-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0022_profile_joinedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='createdProjects',
            field=models.IntegerField(default=0),
        ),
    ]
